services:
  app.exchange_rate.rate.command.pull:
    class: App\Command\PullCommand
    arguments:
      - '@app.exchange_rate.type.analyzer'
      - '@app.exchange_rate.rate.analyzer'
    tags: { - name: console.command }'

  App\Command\PullCommand:
    alias: app.exchange_rate.rate.command.pull
    public: true

