services:
  app.exchange_rate.rate.command.pull:
    class: App\Command\PullCommand
    arguments:
      - '@app.exchange_rate.type.analyzer'
    tags: { - name: console.command }'

  App\Command\PullCommand:
    alias: app.exchange_rate.rate.command.pull
    public: true

  app.exchange_rate.type.analyzer:
    class: App\Command\Analyzer\TypeAnalyzer
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@evrinoma.exchange_rate.type.query.manager"
      - "@evrinoma.exchange_rate.type.command.manager"

  App\Command\Analyzer\TypeAnalyzer:
    alias: app.exchange_rate.type.analyzer
    public: true
