dashboard:
  resource: "@EvrinomaDashBoardBundle/Resources/config/routes.yml"

menu:
  resource: "@EvrinomaMenuBundle/Resources/config/routes.yml"

menu:
  resource: "@EvrinomaVacationBundle/Resources/config/routes.yml"
