dashboard:
  resource: "@EvrinomaDashBoardBundle/Resources/config/routes.yml"

menu:
  resource: "@EvrinomaMenuBundle/Resources/config/routes.yml"

exchange_rate:
  resource: "@EvrinomaExchangeRateBundle/Resources/config/routes.yml"
