dashboard:
  resource: "@EvrinomaDashBoardBundle/Resources/config/routes.yml"

menu:
  resource: "@EvrinomaMenuBundle/Resources/config/routes.yml"

fcr:
  resource: "@EvrinomaFcrBundle/Resources/config/routes.yml"

