# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  mailer_user: "nikolns@ite-ng.ru"
  ldap.servers:
    ite-ng.ru:
      - { host: "ldap://iteng06.ite-ng.ru", port: "636", search: "OU=MSK,DC=ite-ng,DC=ru"}
      - { host: "ldap://iteng20.ite-ng.ru", port: "636", search: "OU=MSK,DC=ite-ng,DC=ru"}
    ur.ite-ng.ru:
      - { host: "ldap://ur04.ur.ite-ng.ru", port: "636", search: "OU=ekaterinburg,DC=ur,DC=ite-ng,DC=ru"}
      - { host: "ldap://ur05.ur.ite-ng.ru", port: "636", search: "OU=ekaterinburg,DC=ur,DC=ite-ng,DC=ru"}

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  #    App\Manager\ModuleManager:
  #        public: true
  Symfony\Component\Security\Http\HttpUtils:
    autowire: true

  App\Security\Ldap:
    arguments:
      $servers: "%ldap.servers%"

  App\Manager\MenuManager:
    arguments: ['@doctrine.orm.entity_manager', '@knp_menu.factory']
    tags:
      - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
