Evrinoma\ExchangeRateBundle\Model\Type\AbstractType:
  exclusion_policy: ALL
  properties:
    id:
      groups: [
          api_get_type, api_post_type, api_put_type, app_get_basic_type,
          api_get_rate, api_post_rate, api_put_rate , app_get_basic_rate
      ]
      expose: true
    identity:
      groups: [
          api_get_type, api_post_type, api_put_type , app_get_basic_type,
          api_get_rate, api_post_rate, api_put_rate , app_get_basic_rate
      ]
      expose: true
